name: pyef
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - openbabel
  - numpy
  - pandas
  - scipy
  - pytest>=6.1.2
  - pytest-cov>=3.0.0
  - basis_set_exchange
  - pip
  - pip:
    - biopandas
